### ISSUE TITLE
Question about extraction of Laboratory values

### ISSUE THREAD

**Issue by whwangyf1234** [AI4HealthUOL/MDS-ED#1]
How are Laboratory values extracted?
As far as I know Laboratory values come from the labevents table and need to be linked to patients from ed via hadm_id. However, many patients (e.g. general_ed_stay_id=33018785) do not have general_ed_hadm_id but have labvalues data. How is this done?
Waiting to get your answer
![image](https://github.com/user-attachments/assets/131d27b6-a758-40df-a7eb-9bc44725b978)

**Comment by juanlopezcode** [comment]
Hi @whwangyf1234,

I understand the concern about the missing hadm_id. However, if you check line 717 in src/full_preprocessing.py, you'll see that I’ve already selected the laboratory values entries that fall within the defined time thresholds (admission to admission + 90 minutes) for a specific patient.

In other words, for a specific patient, the records should match based on a specific date and time.

Hope this helps

Juan
